openapi: 3.0.0
info:
  version: 1.0.0
  title: 'Tammemagi, 6 year Lung Cancer Risk Prediction Model for Screening'
  description: >-
    For adults ages 50 and over, this is a validated lung cancer risk prediction
    model
servers:
  - url: /99999/fk4jh3tk9s/v0.0.3
    description: >-
      For adults ages 50 and over, this is a validated lung cancer risk
      prediction model
tags:
  - name: KO Endpoints
    description: Lung Cancer Risk Score Endpoints
paths:
  /getSixyearprobability:
    post:
      tags:
        - KO Endpoints
      description: Tammemagi.
      operationId: lungcanceriskscore
      requestBody:
        description: inputs
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/input'
      responses:
        '200':
          description: response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/output'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
components:
  schemas:
    input:
      required:
        - age
      properties:
        age:
          type: integer
          example: 65
        ethnicity:
          type: integer
          example: 1
        bmi:
          type: number
          format: float
          example: 27
        cigsPerDay:
          type: integer
          example: 10
        edLevel:
          type: integer
          example: 1
        hxLungCancer:
          type: integer
          example: 1
        hxLungCancerFam:
          type: integer
          example: 1
        hxNonLungCancerDz:
          type: integer
          example: 1
        yrsQuit:
          type: integer
          example: 1
        yrsSmoker:
          type: integer
          example: 20
    output:
      required:
        - result
      properties:
        result:
          type: number
          example: 2.44211
        success:
          type: integer
          example: 1
        errorMessage:
          type: string
    error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
