openapi: 3.0.0
info:
  version: '1.0'
  title: Prostate Cancer Risk Interpreter for Screening Recommendations
  description: >-
    This object accepts as input a prostate cancer risk score and uses it to
    generate prostate cancer screening recommendations.
  license:
    name: GNU General Public License v3 (GPL-3)
    url: >-
      https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)#fulltext
  contact:
    name: KGrid Team
    email: kgrid-developers@umich.edu
    url: 'http://kgrid.org'
servers:
  - url: /99999/fk4n87hh26/1.0
    description: Prostate Cancer Risk Score interpretation
tags:
  - name: KO Endpoints
    description: Prostate Cancer Risk Score interpretation Endpoints
paths:
  /interpretProstateCancerRisk:
    post:
      tags:
        - KO Endpoints
      description: >-
        This object accepts as input a prostate cancer risk score and uses it to
        generate prostate cancer screening recommendations.
      operationId: interp
      requestBody:
        description: inputs
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/input'
      responses:
        '200':
          description: response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/output'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
components:
  schemas:
    input:
      required:
        - highRisk
      properties:
        noRisk:
          type: string
          example: '91.65'
        lowRisk:
          type: string
          example: '6.98'
        highRisk:
          type: string
          example: '1.36'
    output:
      required:
        - result
      properties:
        result:
          type: string
          example: <div class="interpretation"></div>
    error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
