openapi: 3.0.0
info:
  version: 1.0.0
  title: '3-Year Liver Cancer Risk Score Interpreter'
  description: This object accepts a 3-Year Hepatocellular Cancer risk score as input and generates a recommendation depending on an individual's risk of developing liver cancer.
servers:
  - url: '/99999/fk4474n87d/v0.0.2'
    description: Liver Cancer Risk Score interpretation
tags:
  - name: KO Endpoints
    description: Liver Cancer Risk Score interpretation Endpoints
paths:
  /interpretLiverCancerRisk:
    post:
      tags:
        - KO Endpoints
      description: This object interprets an individual's 3-year Hepatocellular Cancer risk.
      operationId: interp
      requestBody:
        description: inputs
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/input'
      responses:
        '200':
          description: response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/output'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
components:
  schemas:
    input:
      required:
        - risk
      properties:
        risk:
          type: number
          format: float
          example: 0.441
    output:
      required:
        - result
      properties:
        result:
          type: string
          example: '<div class="interpretation"></div>'
    error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
