openapi: 3.0.0
info:
  version: 1.0.0
  title: Prostate Cancer Risk Calculator for Men 50 years and older II
  description: This is a prostate cancer risk scoring mechanism
servers:
  - url: /99999/fk4571p57h/v0.0.3
    description: This is a prostate cancer risk scoring mechanism
tags:
  - name: KO Endpoints
    description: Prostate Cancer Risk Score Endpoints
paths:
  /ProstateRiskCalc:
    post:
      tags:
        - KO Endpoints
      description: This is a prostate cancer risk scoring mechanism.
      operationId: prostatecanceriskscore
      requestBody:
        description: inputs
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/input'
      responses:
        '200':
          description: response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/output'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
components:
  schemas:
    input:
      required:
        - Age
      properties:
        Age:
          type: integer
          example: 54
        gender:
          type: string
          example: M
        PSA:
          type: string
          example: '1.1'
        DRE:
          type: integer
          example: 1
        PriorBiop:
          type: integer
          example: 1
        FamHist:
          type: integer
          example: 1
        AA:
          type: integer
          example: 1
    output:
      required:
        - result
      properties:
        result:
          type: array
          example:
            - 91.65637695092367
            - 6.975121390788952
            - 1.3685016582873542
        success:
          type: integer
          example: 1
        errorMessage:
          type: string
    error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
