openapi: 3.0.0
info:
  version: '1.0'
  title: 6 year Lung Cancer Risk Interpretation for Screening Decision-making
  description: >-
    This object interprets an individual's 6-year risk of having lung cancer and
    makes individualized recommendations regarding lung cancer screening.
  license:
    name: GNU General Public License v3 (GPL-3)
    url: >-
      https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)#fulltext
  contact:
    name: KGrid Team
    email: kgrid-developers@umich.edu
    url: 'http://kgrid.org'
servers:
  - url: /99999/fk4805c32z/1.0
    description: Lung Cancer Risk Score interpretation
tags:
  - name: KO Endpoints
    description: Lung Cancer Risk Score interpretation Endpoints
paths:
  /interpretLungCancerRisk:
    post:
      tags:
        - KO Endpoints
      description: This object interprets an individual's 6-year risk.
      operationId: interp
      requestBody:
        description: inputs
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/input'
      responses:
        '200':
          description: response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/output'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
components:
  schemas:
    input:
      required:
        - risk
      properties:
        risk:
          type: number
          format: float
          example: 0.441
    output:
      required:
        - result
      properties:
        result:
          type: string
          example: <div class="interpretation"></div>
    error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
